package vista;

import controlador.AlquilerControlador;
import informes.CrearInformeAlquiler;
import java.io.FileNotFoundException;
import java.sql.SQLException;
import java.time.LocalDate;
import java.time.ZoneId;
import java.util.Date;
import java.util.List;
import javax.swing.JOptionPane;
import modelo.InformeAlquiler;
import net.sf.jasperreports.engine.JRException;

/**
 *
 * @author Luismi
 */
public class VentanaComprobarAlquiler extends javax.swing.JFrame {

    /**
     * Creates new form VentanaPrincipal
     */
    public VentanaComprobarAlquiler() {

        initComponents();

        // centrar la ventana 
        this.setLocationRelativeTo(null);

        //no se pueda deformar la ventana
        this.setResizable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lab_titulo = new javax.swing.JLabel();
        pan_elegirFecha = new javax.swing.JPanel();
        lab_fechaIni = new javax.swing.JLabel();
        cal_fechaInicio = new com.toedter.calendar.JDateChooser();
        lab_fechaFin = new javax.swing.JLabel();
        cal_fechaFin = new com.toedter.calendar.JDateChooser();
        pan_btnComprobar = new javax.swing.JPanel();
        btn_comprobar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Comprobación de alquileres");

        lab_titulo.setFont(new java.awt.Font("Comic Sans MS", 1, 48)); // NOI18N
        lab_titulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lab_titulo.setText("SmartOcupation");

        pan_elegirFecha.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 1, 10, 20));
        pan_elegirFecha.setPreferredSize(new java.awt.Dimension(150, 150));
        pan_elegirFecha.setLayout(new java.awt.GridLayout(2, 2, 0, 30));

        lab_fechaIni.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        lab_fechaIni.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lab_fechaIni.setText("Desde el dia:");
        pan_elegirFecha.add(lab_fechaIni);
        pan_elegirFecha.add(cal_fechaInicio);

        lab_fechaFin.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        lab_fechaFin.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lab_fechaFin.setText("Hasta el dia:");
        pan_elegirFecha.add(lab_fechaFin);
        pan_elegirFecha.add(cal_fechaFin);

        btn_comprobar.setBackground(new java.awt.Color(0, 0, 153));
        btn_comprobar.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        btn_comprobar.setForeground(new java.awt.Color(255, 255, 255));
        btn_comprobar.setText("COMPROBAR");
        btn_comprobar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_comprobarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pan_btnComprobarLayout = new javax.swing.GroupLayout(pan_btnComprobar);
        pan_btnComprobar.setLayout(pan_btnComprobarLayout);
        pan_btnComprobarLayout.setHorizontalGroup(
            pan_btnComprobarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pan_btnComprobarLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btn_comprobar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pan_btnComprobarLayout.setVerticalGroup(
            pan_btnComprobarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pan_btnComprobarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btn_comprobar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(28, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(lab_titulo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pan_elegirFecha, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pan_btnComprobar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(28, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(lab_titulo)
                .addGap(38, 38, 38)
                .addComponent(pan_elegirFecha, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(pan_btnComprobar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    private void btn_comprobarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_comprobarActionPerformed

        // Obtener las fechas del JDateChooser
        Date fechaIni = cal_fechaInicio.getDate();
        Date fechaFin = cal_fechaFin.getDate();

        // Validar que no sean null
        if (fechaIni == null || fechaFin == null) {
            JOptionPane.showMessageDialog(this,
                    "Debes seleccionar ambas fechas",
                    "FALTA FECHAS",
                    javax.swing.JOptionPane.INFORMATION_MESSAGE);
            return;
        }

        // Convertir Date a LocalDate
        LocalDate inicio = fechaIni.toInstant()
                .atZone(ZoneId.systemDefault())
                .toLocalDate();

        LocalDate fin = fechaFin.toInstant()
                .atZone(ZoneId.systemDefault())
                .toLocalDate();

        try {
            AlquilerControlador controller = new AlquilerControlador();

            List<InformeAlquiler> informe = controller.obtenerInformeAlquiler(inicio, fin);

            //Si no hay resultados
            if (informe.isEmpty()) {
                JOptionPane.showMessageDialog(
                        this,
                        "No hay alquileres en el rango seleccionado",
                        "NO HAY RESULTADOS",
                        JOptionPane.INFORMATION_MESSAGE
                );
                return;
            }

            //Mostrar Jasper
            CrearInformeAlquiler.mostrarInforme(informe);

            //Diferentes ventanas de diálogo mostrando errores
        } catch (FileNotFoundException ex) {
            JOptionPane.showMessageDialog(this,
                    "No se encontró la plantilla del informe: " + ex.getMessage(),
                    "ERROR ARCHIVO",
                    JOptionPane.ERROR_MESSAGE);
        } catch (JRException ex) {
            JOptionPane.showMessageDialog(this,
                    "Error generando el informe: " + ex.getMessage(),
                    "ERROR INFORME",
                    JOptionPane.ERROR_MESSAGE);
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this,
                    "No se pudo conectar con la base de datos: " + ex.getMessage(),
                    "ERROR CONEXION",
                    JOptionPane.ERROR_MESSAGE);
        } catch (RuntimeException ex) {
            JOptionPane.showMessageDialog(this,
                    "Error inesperado: " + ex.getMessage(),
                    "ERROR",
                    JOptionPane.ERROR_MESSAGE);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this,
                    "Error inesperado: " + ex.getMessage(),
                    "ERROR",
                    JOptionPane.ERROR_MESSAGE);
        }


    }//GEN-LAST:event_btn_comprobarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new VentanaComprobarAlquiler().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_comprobar;
    private com.toedter.calendar.JDateChooser cal_fechaFin;
    private com.toedter.calendar.JDateChooser cal_fechaInicio;
    private javax.swing.JLabel lab_fechaFin;
    private javax.swing.JLabel lab_fechaIni;
    private javax.swing.JLabel lab_titulo;
    private javax.swing.JPanel pan_btnComprobar;
    private javax.swing.JPanel pan_elegirFecha;
    // End of variables declaration//GEN-END:variables
}
